import { defineConfig } from 'vite'
import { resolve } from 'path'

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        '01': resolve(__dirname, 'pages/01-orbital-observatory.html'),
        '02': resolve(__dirname, 'pages/02-paper-and-ink.html'),
        '03': resolve(__dirname, 'pages/03-terminal-poetic.html'),
        '04': resolve(__dirname, 'pages/04-organic-grid.html'),
        '04a': resolve(__dirname, 'pages/04a-mycelium-network.html'),
        '04b': resolve(__dirname, 'pages/04b-pollen-drift.html'),
        '04c': resolve(__dirname, 'pages/04c-reaction-diffusion.html'),
        '07': resolve(__dirname, 'pages/07-data-landscape.html'),
        '07a': resolve(__dirname, 'pages/07a-erosion-field.html'),
        '07b': resolve(__dirname, 'pages/07b-star-sediment.html'),
        '08': resolve(__dirname, 'pages/08-sine-landscape.html'),
        '08b': resolve(__dirname, 'pages/08b-vertical-strata.html'),
        '08e': resolve(__dirname, 'pages/08e-breath-cascade.html'),
        '10': resolve(__dirname, 'pages/10-zen-algorithm.html'),
        '11': resolve(__dirname, 'pages/11-substrate.html'),
        '12': resolve(__dirname, 'pages/12-mineral-vein.html'),
        '14': resolve(__dirname, 'pages/14-culture.html'),
        '15': resolve(__dirname, 'pages/15-agar.html'),
        '16': resolve(__dirname, 'pages/16-alluvial.html'),
        '17': resolve(__dirname, 'pages/17-stratigraphy.html'),
        '07c': resolve(__dirname, 'pages/07c-phosphor.html'),
        '07d': resolve(__dirname, 'pages/07d-thalweg.html'),
        '07e': resolve(__dirname, 'pages/07e-aureate.html'),
        '07f': resolve(__dirname, 'pages/07f-cirrus.html'),
        '07g': resolve(__dirname, 'pages/07g-verdant.html'),
        '16a': resolve(__dirname, 'pages/16a-sinter.html'),
        '16b': resolve(__dirname, 'pages/16b-littoral.html'),
        '16c': resolve(__dirname, 'pages/16c-cinnabar.html'),
        '16d': resolve(__dirname, 'pages/16d-glacial.html'),
        '16e': resolve(__dirname, 'pages/16e-umbra.html'),
        '07d-amber': resolve(__dirname, 'pages/07d-thalweg-amber.html'),
        '07d-rose': resolve(__dirname, 'pages/07d-thalweg-rose.html'),
        '07d-jade': resolve(__dirname, 'pages/07d-thalweg-jade.html'),
        '07d-bone': resolve(__dirname, 'pages/07d-thalweg-bone.html'),
        '07d-iris': resolve(__dirname, 'pages/07d-thalweg-iris.html'),
        'project-001-a': resolve(__dirname, 'pages/project-001-a.html'),
        'project-001-b': resolve(__dirname, 'pages/project-001-b.html'),
        'project-001-c': resolve(__dirname, 'pages/project-001-c.html'),
        'project-001-d': resolve(__dirname, 'pages/project-001-d.html'),
        'project-001-e': resolve(__dirname, 'pages/project-001-e.html'),
        'card-1': resolve(__dirname, 'pages/07d-thalweg-amber-card-1.html'),
        'card-2': resolve(__dirname, 'pages/07d-thalweg-amber-card-2.html'),
        'card-3': resolve(__dirname, 'pages/07d-thalweg-amber-card-3.html'),
        'card-4': resolve(__dirname, 'pages/07d-thalweg-amber-card-4.html'),
        'card-5': resolve(__dirname, 'pages/07d-thalweg-amber-card-5.html'),
        'card': resolve(__dirname, 'pages/07d-thalweg-amber-card.html'),
      },
    },
  },
})
